services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'myrasabot'
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'
    volumes:
       - ./myrasabot-dump.sql:/docker-entrypoint-initdb.d/myrasabot-dump.sql
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.00'
        reservations:
          memory: 512M
          cpus: '0.50'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  rasa_action_server:
    build:
      context: .
      dockerfile: Dockerfile.actions
    depends_on:
      db:
        condition: service_healthy
    ports:  
      - "5055:5055"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.50'
        reservations:
          memory: 256M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5055/health"]
      interval: 30s
      retries: 6
      start_period: 30s
      timeout: 10s

  rasa_server:
    build:
      context: .
      dockerfile: Dockerfile.rasa
    depends_on:
      rasa_action_server:
        condition: service_healthy
    ports:  
      - "5005:5005"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.75'
        reservations:
          memory: 512M
          cpus: '0.50'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005"]
      interval: 30s
      retries: 6
      start_period: 60s
      timeout: 10s

  front_end:
    build:
      context: .
      dockerfile: Dockerfile.frontEnd
    depends_on:
      rasa_server:
        condition: service_healthy
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.50'
        reservations:
          memory: 256M
          cpus: '0.25'
